title: Lucy Emmanuel
image: "C:/Users/b/Pictures/IMG_0051-removebg-preview-removebg-preview-removebg-preview.png"
description: Welcome to my data science portfolio! I'm Lucy Emmanuel, an aspiring data scientist passionate about turning raw data into meaningful insights. Explore my projects and discover how I leverage Python, SQL, AWS, Snowflake, and MATLAB to tackle diverse challenges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
theme: jekyll-theme-minimal

# Owner information
author:
  name: Lucy Emmanuel

# GitHub repository settings
repository:
  name: example-portfolio
  owner: Lucy Emmanuel


